apiVersion: v1
kind: Service

metadata:
  name: svc-wordpress
  labels:
    app: web-wordpress
    version: v1

spec:
  type: LoadBalancer
  selector:
    microservice: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   